version: '3.2'

services:
    api:
        build: ../..
        container_name: ever-api-dev
        ports:
            - 5501:5501
        environment:
            - DB_URI=mongodb://mongodb/ever_development
        links:
            - mongodb
        depends_on:
            - mongodb

    mongodb:
        image: mongo
        container_name: mongodb
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
